import {SCHEMA,CUTS,PAIRS,CODES,label,clone,key,validDate,createDocument,inspect,fromLegacy} from './model.js';
const q=new URLSearchParams(location.search),local=q.get('local'),API='https://evmgsqdrojxppxknrzfk.supabase.co/functions/v1/photo-ledger-v2';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let doc=createDocument(q),revision=0,capture=doc.case.work_date,storageKey='',busy=false,dirty=false,hydrating=true;
const cursors={};
function get(path){return path.split('.').reduce((o,k)=>o?.[k],doc);}
function set(path,value){const keys=path.split('.');let o=doc;for(const k of keys.slice(0,-1))o=o[k];o[keys.at(-1)]=value;}
function field(path,title,{numeric=false,type='text',value}={}){return `<label>${esc(title)}<input data-path="${path}" ${numeric?'inputmode="numeric"':''} type="${type}" value="${esc(value??get(path)??'')}"></label>`;}
const button=(action,text,attrs='',cls='secondary')=>`<button type="button" class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;
function say(text,bad=false){$('#load-status').textContent=text;$('#load-status').className=bad?'notice':'';}
function chooseKey(){storageKey=`ippatsu-ledger-v2:${doc.case.case_id||doc.case.management_no.replace(/\D/g,'')+':'+doc.case.work_date}`;}
function persist(){if(hydrating)return;dirty=true;try{const old=localStorage.getItem(storageKey);if(old)localStorage.setItem(storageKey+':backup',old);localStorage.setItem(storageKey,JSON.stringify({document:doc,revision,dirty:true,updated_at:new Date().toISOString()}));$('#save-state').textContent=local?'ブラウザに下書き保存済み · PCへ反映は下の保存ボタン':'端末に保存済み · ポータルは未保存';}catch(e){$('#save-state').textContent='端末保存できません。ファイル保存かポータル保存をしてください：'+e.message;}updateStatus();}
function updateStatus(){const s=inspect(doc);$('#overview').innerHTML=`<h2>入力の確認</h2><div class="stats"><span class="pill">枝切り写真 ${s.branchPhotos}枚</span><span class="pill">掲載写真 ${s.photos}枠</span><span class="pill ${s.errors.length?'short':'ok'}">${s.errors.length?'印刷前に確認 '+s.errors.length+'件':'入力形式 OK'}</span></div>${s.errors.length?'<ul class="issues">'+s.errors.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>':''}${s.warnings.length?'<details><summary>予定に対する不足 '+s.warnings.length+'件</summary><ul class="issues">'+s.warnings.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul></details>':''}<small>途中の内容も保存できます。写真ファイルはPCで照合します。</small>`;
for(const c of CUTS){const el=document.getElementById('stat-'+c),n=s.counts[c];if(el)el.innerHTML=`<span class="pill ${!n.exact?'bad':n.total<n.planned?'short':n.total>n.planned?'added':'ok'}">予定 ${n.planned}本 ／ 入力 ${n.total}本 ／ ${n.photos}枚</span><span class="pill">${n.total>n.planned?'追加 '+(n.total-n.planned)+'本':'残り '+(n.planned-n.total)+'本'}</span>`;}}
function render(){
$('#case-label').textContent=doc.case.span_label||'新しい案件';$('#case-meta').textContent=`${doc.case.management_no}　作業日 ${doc.case.work_date}`;$('#design').value=doc.case.design_no;$('#capture').value=capture;
$('#plan-fields').innerHTML=field('case.management_no','管理番号')+field('case.span_label','径間名')+field('case.work_date','台帳をまとめる作業日',{numeric:true})+`<p class="muted">この台帳の規定/追加の基準です。案件DBの予定は変更しません。</p><div class="plan-row"><b>サイズ</b><b>枝切り</b><b>根切り</b>${[10,20,30,40,50,60].map(n=>`<span>${n===60?'50cm以上':n+'cm未満'}</span>${field('case.planned.E'+n,'E'+n,{numeric:true,type:'number'})}${field('case.planned.N'+n,'N'+n,{numeric:true,type:'number'})}`).join('')}</div>`+['TK','TR','SB'].map(c=>field('case.planned.'+c,`${label(c)} ${c==='SB'?'㎡':c==='TR'?'箇所':'本'}`,{numeric:true,type:'number'})).join('');
$('#choices').innerHTML=CODES.map(c=>`${['E10','N10','TK'].includes(c)?`<div class="group-heading">${c==='E10'?'枝切り':c==='N10'?'根切り':'その他'}</div>`:''}<button type="button" data-action="toggle" data-code="${c}" aria-pressed="${doc.selected.includes(c)}">${esc(CUTS.includes(c)?c:label(c))}</button>`).join('');
$('#form').innerHTML=CODES.filter(c=>doc.selected.includes(c)).map(c=>`<section id="section-${c}"><h2>${esc(label(c))}</h2>${PAIRS.includes(c)?renderPairs(c):CUTS.includes(c)?renderCuts(c):renderLines(c)}</section>`).join('');
$('#adjustments').innerHTML=doc.adjustments.map((r,i)=>`<div class="entry"><div class="row">${field(`adjustments.${i}.date`,'撮影日',{numeric:true})}${field(`adjustments.${i}.no`,'写真番号',{numeric:true})}</div><label>回転<select data-path="adjustments.${i}.rotation" data-number="1">${[0,90,180,270].map(n=>`<option value="${n}" ${r.rotation===n?'selected':''}>${n===0?'EXIFどおり':n===90?'右に90°':n===180?'上下反転':'左に90°'}</option>`).join('')}</select></label><label class="check"><input type="checkbox" data-path="adjustments.${i}.banner" ${r.banner?'checked':''}>崖のためサシあて困難</label>${button('remove','削除',`data-path="adjustments" data-index="${i}"`,'danger')}</div>`).join('');updateStatus();
}
function renderPairs(c){return (doc.pairs[c]||[]).map((r,i)=>`<div class="entry"><div class="pair-title"><b>${i+1}組目</b><div>${button('up','↑',`data-path="pairs.${c}" data-index="${i}"`)} ${button('down','↓',`data-path="pairs.${c}" data-index="${i}"`)} ${button('remove','削除',`data-path="pairs.${c}" data-index="${i}"`,'danger')}</div></div><div class="row">${['before','after'].map(side=>`<div class="pair-side"><b>${side==='before'?'前':'後'}</b>${field(`pairs.${c}.${i}.${side}.date`,'撮影日',{numeric:true})}${field(`pairs.${c}.${i}.${side}.no`,'写真番号',{numeric:true})}</div>`).join('')}</div></div>`).join('')+button('add-pair','＋ 前後の組を追加',`data-code="${c}"`)+(c!=='BA'&&doc.pairs.BA.length?`<details><summary>伐採前後から流用</summary>${doc.pairs.BA.map((p,i)=>button('reuse',`${i+1}組目 ${esc(p.before.no)} → ${esc(p.after.no)} を追加`,`data-code="${c}" data-index="${i}"`)).join('')}</details>`:'');}
function renderCuts(c){const rows=doc.cuts[c]||[],last=rows.at(-1);cursors[c]??={date:capture,no:last?String(+last.no+1).padStart(3,'0'):''};const cursor=cursors[c];return `<div id="stat-${c}" class="stats"></div><div class="chips">${rows.map(r=>`<span class="chip">${esc(r.no)} <em>${r.count}本</em></span>`).join('')}</div><div class="row"><label>撮影日<input data-cursor="${c}" data-prop="date" inputmode="numeric" value="${esc(cursor.date)}"></label><label>${['E10','N10'].includes(c)?'次の写真番号':'写真番号（カンマ区切り）'}<input data-cursor="${c}" data-prop="no" inputmode="${['E10','N10'].includes(c)?'numeric':'text'}" value="${esc(cursor.no)}" placeholder="001"></label></div>${['E10','N10'].includes(c)?`<details open><summary>本数を押して次の写真へ</summary><div class="keys">${[1,2,3,4,5,6,7,8,9].map(n=>button('count',String(n),`data-code="${c}" data-count="${n}"`,'key')).join('')}${button('back','⌫ 直前の写真を取り消す',`data-code="${c}"`,'back')}</div></details>`:button('add-photos','写真を追加（1枚1本）',`data-code="${c}"`)}<details><summary>登録した写真・本数を修正（${rows.length}枚）</summary>${rows.map((r,i)=>`<div class="photo-edit">${field(`cuts.${c}.${i}.date`,'撮影日',{numeric:true})}${field(`cuts.${c}.${i}.no`,'写真',{numeric:true})}${field(`cuts.${c}.${i}.count`,'本数',{numeric:true,type:'number'})}${button('remove','×',`data-path="cuts.${c}" data-index="${i}"`,'danger')}</div>`).join('')}</details>`;}
function renderLines(c){const f=c==='US'?'transport':'special';return doc[f].map((r,i)=>{if(c!=='US'&&r.code!==c)return '';const p=`${f}.${i}`;return `<div class="entry">${c==='US'?`<div class="row"><label>車種<select data-vehicle="${i}"><option ${r.label.includes('軽四輪')?'selected':''}>軽四輪</option><option ${r.label.includes('2t車')?'selected':''}>2t車</option></select></label><label class="check"><input type="checkbox" data-specified="${i}" ${r.label.startsWith('指定場所')?'checked':''}>指定場所運搬</label></div>`:c==='FR'?field(p+'.label','区分名'):''}<div class="row"><label>撮影日<input data-line-date="${p}" value="${esc(r.photos[0]?.date||capture)}" inputmode="numeric"></label><label>写真番号（カンマ区切り）<input data-line-photos="${p}" value="${esc(r.photos.map(x=>x.no).join(','))}" placeholder="001,002"></label></div><small>複数日の場合は行を分けて追加してください。</small>${button('remove','この行を削除',`data-path="${f}" data-index="${i}"`,'danger')}</div>`;}).join('')+button('add-line','＋ '+label(c)+'を追加',`data-code="${c}"`);}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.path){let value=t.type==='checkbox'?t.checked:t.type==='number'||t.dataset.number?Number(t.value):t.value;set(t.dataset.path,value);persist();}else if(t.dataset.cursor){cursors[t.dataset.cursor][t.dataset.prop]=t.value;}else if(t.id==='design'){doc.case.design_no=t.value;persist();}else if(t.id==='capture'){capture=t.value;}else if(t.dataset.linePhotos||t.dataset.lineDate){const p=t.dataset.linePhotos||t.dataset.lineDate,row=get(p),date=document.querySelector(`[data-line-date="${p}"]`).value,numbers=document.querySelector(`[data-line-photos="${p}"]`).value;row.photos=numbers.split(/[,、\s]+/).filter(Boolean).map(no=>({date,no:no.padStart(3,'0')}));persist();}else if(t.dataset.vehicle!==undefined||t.dataset.specified!==undefined){const i=t.dataset.vehicle??t.dataset.specified,v=document.querySelector(`[data-vehicle="${i}"]`).value,s=document.querySelector(`[data-specified="${i}"]`).checked;doc.transport[i].label=(s?'指定場所運搬':'運　搬　')+' '+v;persist();}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,c=b.dataset.code,i=Number(b.dataset.index),path=b.dataset.path;try{
if(a==='toggle'){doc.selected=doc.selected.includes(c)?doc.selected.filter(x=>x!==c):[...doc.selected,c];}
if(a==='add-pair')doc.pairs[c].push({before:{date:capture,no:''},after:{date:capture,no:''}});
if(a==='reuse')doc.pairs[c].push(clone(doc.pairs.BA[i]));
if(a==='remove')get(path).splice(i,1);
if(a==='up'&&i>0){const arr=get(path);[arr[i-1],arr[i]]=[arr[i],arr[i-1]];}
if(a==='down'&&i<get(path).length-1){const arr=get(path);[arr[i+1],arr[i]]=[arr[i],arr[i+1]];}
if(a==='add-line'){const field=c==='US'?'transport':'special';doc[field].push({code:c,label:c==='US'?'運　搬　 2t車':c==='DF'?'倒木実費':'',photos:[]});}
if(a==='count'||a==='add-photos'){const cur=cursors[c];if(!validDate(cur.date))throw Error('撮影日を6桁で入力してください');const nums=a==='count'?[cur.no]:cur.no.split(/[,、\s]+/).filter(Boolean);if(!nums.length||nums.some(n=>!/^\d{1,3}$/.test(n)))throw Error('写真番号を1～3桁で入力してください');for(const n of nums){const row={date:cur.date,no:n.padStart(3,'0'),count:a==='count'?+b.dataset.count:1};if(doc.cuts[c].some(x=>key(x)===key(row)))throw Error(`写真${row.no}は登録済みです。修正欄から変更できます`);}doc.cuts[c].push(...nums.map(n=>({date:cur.date,no:n.padStart(3,'0'),count:a==='count'?+b.dataset.count:1})));cur.no=a==='count'&&+nums[0]<999?String(+nums[0]+1).padStart(3,'0'):'';}
if(a==='back'){const r=doc.cuts[c].pop();if(r)cursors[c]={date:r.date,no:r.no};}
persist();render();}catch(err){say(err.message,true);}});
$('#add-adjustment').onclick=()=>{doc.adjustments.push({date:capture,no:'',rotation:0,banner:true});persist();render();};
$('#download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));a.download=`台帳新版_${doc.case.work_date}_${doc.case.management_no.replace(/\D/g,'')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#import').onchange=async e=>{try{const loaded=fromLegacy(JSON.parse(await e.target.files[0].text()));if(!confirm('この画面にファイルの内容を読み込みます。よろしいですか？'))return;doc=loaded;revision=0;chooseKey();capture=doc.case.work_date;persist();render();say('ファイルを読み込みました。撮影日も確認してください。');}catch(e){say('読込できません：'+e.message,true);}};
$('#restore').onclick=()=>{const raw=localStorage.getItem(storageKey+':backup');if(!raw)return say('端末のバックアップがありません');if(confirm('直前の端末下書きに戻しますか？')){const saved=JSON.parse(raw);doc=saved.document;revision=saved.revision;persist();render();}};
async function request(params={},body){const url=local?'/api/document?local='+encodeURIComponent(local):API+'?'+new URLSearchParams(params);let response;try{response=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});}catch(e){throw Error('通信できません。端末には入力を残しています。ネット接続を確認して再度保存してください。');}let data;try{data=await response.json();}catch{throw Error('保存先から正しい応答がありません。入力は端末に残っています。');}if(!response.ok)throw Error(data.message||`保存先エラー（${response.status}）。入力は端末に残っています。`);return data;}
async function saveCloud(){
if(busy)return;busy=true;$('#cloud-save').disabled=true;
try{
if(!doc.case.span_label||!/^\d{8}$/.test(doc.case.management_no.replace(/\D/g,''))||!validDate(doc.case.work_date))throw Error('案件情報の管理番号・径間名・作業日を確認してください');
const sent=clone(doc),result=await request({}, {document:sent,expected_revision:revision});revision=result.revision;
const read=await request({id:sent.id});if(JSON.stringify(sort(read.document))!==JSON.stringify(sort(sent)))throw Error('保存後の読戻しが一致しません。端末内容は保持しています');
dirty=JSON.stringify(doc)!==JSON.stringify(sent);
localStorage.setItem(storageKey,JSON.stringify({document:doc,revision,dirty,updated_at:new Date().toISOString()}));
$('#save-state').textContent=dirty?'保存中に追加入力あり · もう一度保存してください':`${local?'PCに':'ポータルに'}保存・読戻し確認済み（${new Date().toLocaleTimeString()}）`;
say('保存しました。未入力や不足があっても、続きから入力できます。');
}catch(e){say(e.message,true);}finally{busy=false;$('#cloud-save').disabled=false;}}
function sort(x){return Array.isArray(x)?x.map(sort):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):x;}
$('#cloud-save').onclick=saveCloud;
$('#reload-cloud').onclick=async()=>{if(!confirm('端末の現在の入力はバックアップし、ポータル保存の内容を読み直しますか？'))return;try{const saved=await request({id:doc.id});if(!saved.document)throw Error('保存済みデータがありません');doc=saved.document;revision=saved.revision;persist();render();say('保存済みの内容を読み込みました');}catch(e){say(e.message,true);}};
async function start(){
$('#old-link').href='../ledger-input/?'+q.toString();let cached=null;
// Restore before network access so a disconnected field visit is immediately usable.
if(!local){try{const number=doc.case.management_no.replace(/\D/g,'');const candidates=Object.keys(localStorage).filter(k=>k.startsWith('ippatsu-ledger-v2:')&&!k.endsWith(':backup')).map(k=>{try{return JSON.parse(localStorage.getItem(k));}catch{return null;}}).filter(x=>x?.document?.schema===SCHEMA&&x.document.case.management_no.replace(/\D/g,'')===number);const sameDay=candidates.filter(x=>x.document.case.work_date===doc.case.work_date);cached=sameDay.length===1?sameDay[0]:candidates.length===1?candidates[0]:null;if(cached){doc=clone(cached.document);revision=cached.revision||0;if(q.get('date'))doc.case.work_date=q.get('date');}}catch(e){say('端末下書きの読込に失敗しました。元の保存は削除していません。',true);}}
chooseKey();capture=doc.case.work_date;render();hydrating=false;
if(cached)$('#save-state').textContent='端末の入力を復元済み · 通信確認中';
if(local){$('#cloud-save').textContent='修正をPCに保存';$('#old-link').hidden=true;}else if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
try{const data=await request({date:doc.case.work_date,management_no:doc.case.management_no});
if(dirty){if(data.case&&!doc.case.case_id&&!data.document){doc.case.case_id=data.case.case_id;doc.id=data.case.case_id;chooseKey();persist();}say('通信中の入力を保持しました。保存前に案件情報をご確認ください。');return;}
if(local){doc=data.document;revision=data.revision||0;chooseKey();try{const localDraft=JSON.parse(localStorage.getItem(storageKey)||'null');if(localDraft?.dirty&&localDraft.document.id===doc.id){doc=localDraft.document;dirty=true;say('ブラウザに残っていた未反映の入力を復元しました。');}}catch{}}
else if(data.case){
const source=data.case;
if(cached&&cached.document.case.case_id&&cached.document.case.case_id!==source.case_id){say('同じ管理番号の別作業の下書きがあります。現在の案件を開きました。以前の下書きは保持しています。');cached=null;doc=createDocument(q);revision=0;}
if(cached&&cached.revision!==data.revision&&data.document){say('端末とポータルに異なる保存があります。端末入力を開いています。必要なら「ポータル保存を読み直す」で比較してください。',true);}
else if(data.document&&!cached){doc=data.document;revision=data.revision;}
else if(!cached){doc.case={...doc.case,...source,planned:source.planned,original_planned:clone(source.planned)};const p=doc.case.planned,bamboo=p.TK>0&&!CUTS.some(c=>p[c])&&!p.SB&&!p.TR;doc.selected=CODES.filter(c=>c==='BA'?!bamboo:p[c]>0);}
if(!doc.case.design_no)doc.case.design_no=source.design_no||'';
doc.case.case_id=source.case_id;doc.id=source.case_id;
const day=q.get('date');if(day&&day!==doc.case.work_date){doc.case.work_date=day;say('前回の入力を持ち越しました。写真の撮影日は保持しています。');}
}
chooseKey();localStorage.setItem(storageKey,JSON.stringify({document:doc,revision,dirty:dirty||!!cached?.dirty,updated_at:new Date().toISOString()}));capture=doc.case.work_date;render();if(cached)$('#save-state').textContent='端末の入力を復元しました';
}catch(e){say(e.message,true);}
if(q.get('edit_plan'))$('#plan').open=true;
if(!local){$('#history').innerHTML='<button type="button" class="secondary" id="show-history">ポータルの保存履歴を表示</button>';$('#show-history').onclick=async()=>{try{const data=await request({id:doc.id,history:'1'});$('#history').innerHTML=(data.items||[]).map(r=>`<p><button type="button" class="link" data-version="${r.revision}">${esc(r.saved_at)} の内容を開く（版${r.revision}）</button></p>`).join('')||'保存履歴はありません';}catch(e){say(e.message,true);}};}
}
$('#history').onclick=async e=>{const v=e.target.dataset.version;if(!v)return;try{const result=await request({id:doc.id,revision:v});doc=result.document;persist();render();say('以前の内容を開きました。ポータル保存すると新しい版として残ります。');}catch(e){say(e.message,true);}};
start();
