export const SCHEMA='ippatsu-photo-ledger/v2';
export const CUTS=['E','N'].flatMap(k=>[10,20,30,40,50,60].map(n=>k+n));
export const PAIRS=['BA','TK','TR','SB'];
export const CODES=['BA',...CUTS,'TK','TR','SB','US','DF','FR'];
export const LABELS={BA:'伐採前後',TK:'竹伐採前後',TR:'つる伐採前後',SB:'柴伐採前後',US:'運搬',DF:'倒木実費',FR:'自由記述'};
export const label=c=>LABELS[c]||`${c[0]==='E'?'枝切り':'根切り'} ${c.slice(1)==='60'?'50cm以上':c.slice(1)+'cm未満'}`;
export const clone=x=>JSON.parse(JSON.stringify(x));
export const key=p=>`${p.date}:${String(p.no).padStart(3,'0')}`;
export function validDate(s){if(!/^\d{6}$/.test(s))return false;const d=new Date(2000+ +s.slice(0,2),+s.slice(2,4)-1,+s.slice(4));return d.getFullYear()===2000+ +s.slice(0,2)&&d.getMonth()===+s.slice(2,4)-1&&d.getDate()===+s.slice(4);}
export const validRef=p=>p&&validDate(p.date)&&/^\d{1,3}$/.test(String(p.no));
export function partition(rows,target){const sums=new Map([[0,[]]]);rows.forEach((r,i)=>[...sums].forEach(([n,ids])=>{const next=n+Number(r.count);if(next<=target&&!sums.has(next))sums.set(next,[...ids,i]);}));const total=rows.reduce((a,r)=>a+Number(r.count||0),0),chosen=new Set(total<=target?rows.map((_,i)=>i):sums.get(target)||[]);let n=1;return {exact:total<=target||sums.has(target),total,ordered:[...rows.filter((_,i)=>chosen.has(i)).map(r=>({...r,claim:'PLANNED'})),...rows.filter((_,i)=>!chosen.has(i)).map(r=>({...r,claim:'ADDED'}))].map(r=>{const out={...r,start:n,end:n+ +r.count-1};n+= +r.count;return out;})};}
export function createDocument(q){const date=q.get('date')||new Date().toLocaleDateString('sv').replaceAll('-','').slice(2);const planned=Object.fromEntries([...CUTS,'TK','TR','SB'].map(c=>[c,Math.max(0,parseInt(q.get(c)||'0')||0)]));const bambooOnly=planned.TK>0&&!CUTS.some(c=>planned[c])&&!planned.SB&&!planned.TR;return {schema:SCHEMA,id:crypto.randomUUID(),case:{case_id:'',management_no:q.get('management_no')||'',span_label:q.get('label')||'',work_date:date,design_no:q.get('design_no')||'',planned,original_planned:clone(planned)},selected:CODES.filter(c=>c==='BA'?!bambooOnly:planned[c]>0),pairs:Object.fromEntries(PAIRS.map(c=>[c,[]])),cuts:Object.fromEntries(CUTS.map(c=>[c,[]])),transport:[],special:[],adjustments:[]};}
export function inspect(d){const errors=[],warnings=[],counts={};let photos=0;const sel=d.selected||[],p=d.case.planned||{};
if(!validDate(d.case.work_date))errors.push('作業日は6桁の有効な日付で入力してください');
for(const c of CUTS)if(!Number.isInteger(Number(p[c]||0))||Number(p[c]||0)<0||Number(p[c]||0)>100000)errors.push(`${c}：予定本数は0以上の整数で入力してください`);
if(!/^(B\s*)?\d{1,4}$/i.test(d.case.design_no.trim()))errors.push('設計番号を入力してください（例 B 6251）');
if(!/^\d{8}$/.test(d.case.management_no.replace(/\D/g,'')))errors.push('管理番号は8桁で入力してください');
if(!d.case.span_label)errors.push('径間名を入力してください');
for(const c of PAIRS){if(!sel.includes(c))continue;const rows=d.pairs[c]||[];if(!rows.length)errors.push(`${label(c)}：前後写真を登録してください`);rows.forEach((r,i)=>{for(const side of ['before','after'])if(!validRef(r[side]))errors.push(`${label(c)} ${i+1}組目：${side==='before'?'前':'後'}の撮影日・番号を確認`);if(validRef(r.before)&&validRef(r.after)&&key(r.before)===key(r.after))errors.push(`${label(c)} ${i+1}組目：前後が同じ写真です`);photos+=2;});}
for(const c of CUTS){const rows=sel.includes(c)?d.cuts[c]||[]:[],part=partition(rows,Number(p[c]||0));counts[c]={...part,photos:rows.length,planned:Number(p[c]||0)};if(sel.includes(c)&&!rows.length)errors.push(`${c}：写真が未入力です`);const seen=new Set();rows.forEach(r=>{if(!validRef(r))errors.push(`${c}：撮影日・写真番号を確認`);if(!Number.isInteger(r.count)||r.count<1||r.count>9||(!['E10','N10'].includes(c)&&r.count!==1))errors.push(`${c}：本数を確認`);if(seen.has(key(r)))errors.push(`${c}：写真${key(r)}が重複`);seen.add(key(r));});if(!part.exact)errors.push(`${c}：写真単位で予定${p[c]}本ちょうどにできません`);if(part.total< +p[c])warnings.push(`${c}：残り${p[c]-part.total}本（予定${p[c]} / 入力${part.total}）`);photos+=rows.length;}
for(const c of ['US','DF','FR']){if(!sel.includes(c))continue;const rows=(c==='US'?d.transport:d.special.filter(r=>r.code===c));if(!rows.length)errors.push(`${label(c)}：写真を入力してください`);for(const row of rows){if(!row.label.trim()||!row.photos.length)errors.push(`${label(c)}：区分と写真番号を入力`);for(const r of row.photos)if(!validRef(r))errors.push(`${label(c)}：写真の撮影日・番号を確認`);photos+=row.photos.length;}}
if(!photos)errors.push('採用写真がありません');return {errors:[...new Set(errors)],warnings,counts,branchPhotos:CUTS.filter(c=>c[0]==='E').reduce((s,c)=>s+counts[c].photos,0),photos};}
export function fromLegacy(old){if(old.schema===SCHEMA)return clone(old);if(old.schema!=='ippatsu-photo-ledger-instruction/v1')throw Error('対応していないJSONです');const q=new URLSearchParams({date:old.case.share_date_key,management_no:old.case.management_no,label:old.case.span_label}),d=createDocument(q),date=q.get('date');d.case={...d.case,...old.case,work_date:date,planned:{...old.case.planned,...old.case.plan_adjustment?.final}};d.selected=[];const r=no=>({date,no:String(no).padStart(3,'0')});for(const c of PAIRS){d.pairs[c]=(old.pairs?.[c]||[]).map(x=>({before:r(x.before),after:r(x.after)}));if(d.pairs[c].length)d.selected.push(c);}for(const c of CUTS){d.cuts[c]=(old.cuts?.[c]||[]).flatMap(x=>['E10','N10'].includes(c)?x.counts.map((count,i)=>({...r(+x.start_photo+i),count})):[{...r(x),count:1}]);if(d.cuts[c].length)d.selected.push(c);}for(const f of ['transport','special'])for(const row of old[f]||[]){const code=f==='transport'?'US':row.label==='倒木実費'?'DF':'FR';d[f].push({code,label:row.label,photos:row.photos.map(r)});if(!d.selected.includes(code))d.selected.push(code);}return d;}
