(() => {
"use strict";
const q=new URLSearchParams(location.search), codes=["BA","E10","E20","E30","E40","E50","E60","N10","N20","N30","N40","N50","N60","TK","TR","SB","US","DF","FR"], cuts=codes.filter(x=>/^[EN]\d\d$/.test(x)), pairs=["BA","TK","TR","SB"], bands=[["E10","N10","〜10cm未満"],["E20","N20","〜20cm未満"],["E30","N30","〜30cm未満"],["E40","N40","〜40cm未満"],["E50","N50","〜50cm未満"],["E60","N60","50cm以上"]], others=[["SB","brush_area_m2","柴伐採面積（㎡）"],["TK","bamboo_count","竹伐採本数"],["TR","vine_locations","つる伐採箇所数"]], labels={BA:"伐採前後",E10:"E10",E20:"E20",E30:"E30",E40:"E40",E50:"E50",E60:"E60",N10:"N10",N20:"N20",N30:"N30",N40:"N40",N50:"N50",N60:"N60",TK:"竹伐採前後",TR:"つる伐採前後",SB:"柴伐採前後",US:"運搬",DF:"倒木実費",FR:"自由記述"}, mno=q.get("management_no")||"",span=q.get("label")||"",form=document.querySelector("#form"),choices=document.querySelector("#choices"),message=document.querySelector("#message"),planEdit=document.querySelector("#plan-edit"),planCut=document.querySelector("#plan-cut-fields"),planOther=document.querySelector("#plan-other-fields"),planSummary=document.querySelector("#plan-summary"),designInput=document.querySelector("#design"),planDesignInput=document.querySelector("#plan-design");
const integer=v=>Math.max(0,Number.parseInt(v,10)||0), base=Object.fromEntries([...cuts,...others.map(([,k])=>k)].map(k=>[k,integer(q.get(k)||0)]));base.bamboo_count=integer(q.get("TK")||base.bamboo_count);base.brush_area_m2=integer(q.get("SB")||base.brush_area_m2);base.vine_locations=integer(q.get("TR")||base.vine_locations);let plan={...base};
const oldKey=`ippatsu-photo-ledger-draft:${[q.get("date")||"",mno,span].join(":")}`,key=`ippatsu-photo-ledger-draft:v2:${[q.get("date")||"",mno].join(":")}`,backupKey=`${key}:backup`,olderBackupKey=`${key}:backup-previous`,portalDraftEndpoint="https://evmgsqdrojxppxknrzfk.supabase.co/functions/v1/photo-ledger-instruction-drafts";
document.querySelector("#case").textContent=`${mno}　${span}`;const say=(t,k="")=>{message.textContent=t;message.className=`message ${k}`.trim()},no=v=>{v=String(v||"").trim();if(!/^\d{1,3}$/.test(v))throw Error("写真番号は1〜3桁の数字です");return v.padStart(3,"0")},photos=v=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean).map(no),chosen=()=>[...choices.querySelectorAll("[aria-pressed=true]")].map(x=>x.dataset.code),qty=c=>c==="TK"?plan.bamboo_count:c==="SB"?plan.brush_area_m2:c==="TR"?plan.vine_locations:plan[c]||0,defaults=()=>codes.filter(c=>c==="BA"||qty(c)>0);
function part(rows,target){const reached=new Map([[0,[]]]);rows.forEach((r,i)=>[...reached].forEach(([sum,ids])=>{const next=sum+r.count;if(next<=target&&!reached.has(next))reached.set(next,[...ids,i])}));const exact=reached.has(target),set=new Set(reached.get(exact?target:Math.max(...reached.keys())));return{exact,planned:rows.filter((_,i)=>set.has(i)),added:rows.filter((_,i)=>!set.has(i))}}
const pair=(a="",b="")=>`<div class="pair"><label>前<input class="before" inputmode="numeric" value="${a}"></label><label>後<input class="after" inputmode="numeric" value="${b}"></label></div>`,run=(s="",v=[],p="")=>`<div class="run" data-counts="${v.join(",")}" data-pending="${p}"><label>開始写真番号<input class="start" inputmode="numeric" value="${s}" placeholder="001"></label><label>写真ごとの本数</label><div class="counts"></div><div class="keys">${[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" class="key" data-key="${n}">${n}</button>`).join("")}<button type="button" class="key" data-key="back">⌫</button></div><small class="pending"></small></div>`,transport=(v="軽四輪",s=false,p="")=>`<div class="transport-row"><label>車種<select class="vehicle"><option ${v==="軽四輪"?"selected":""}>軽四輪</option><option ${v==="2t車"?"selected":""}>2t車</option></select></label><label>写真番号（カンマ区切り）<input class="transport-photos" inputmode="numeric" value="${p}"></label><label class="transport-check"><input class="specified" type="checkbox" ${s?"checked":""}>指定場所運搬にする</label></div>`;
function html(c){if(pairs.includes(c))return `<section data-s="${c}"><h2>${labels[c]}</h2><small>採用する組だけ入力します。</small><div class="pair-list">${pair()}</div><button type="button" class="secondary add-pair">＋ 前後1組を追加</button>${c==="TK"?'<label>BA流用する組番号（例: 1,2）<input class="reuse" inputmode="numeric"></label><p class="note">指定したBA組だけを竹伐採前後にも使います。</p>':""}</section>`;if(c==="E10"||c==="N10")return `<section data-s="${c}"><h2>${c} <span class="status summary"></span></h2><small>1〜9を押すと、その写真の本数として即時確定します。⌫で最後の本数を取り消せます。写真番号が飛ぶ時だけ続きの写真を追加。</small><div class="runs">${run()}</div><button type="button" class="secondary add-run">＋ 続きの写真を追加</button><p class="status state" aria-live="polite"></p><p class="note preview"></p></section>`;if(cuts.includes(c))return `<section data-s="${c}"><h2>${c} <span class="status summary"></span></h2><small>1本につき写真1枚です。</small><label>写真番号（カンマ区切り）<input class="photos" inputmode="numeric" placeholder="001, 002"></label><p class="status state" aria-live="polite"></p></section>`;if(c==="US")return `<section data-s="US"><h2>運搬</h2><small>車種を選び、チェック中だけ「指定場所運搬」として保存します。</small><div class="transport-list">${transport()}</div><button type="button" class="secondary add-transport">＋ 運搬を追加</button></section>`;if(c==="DF")return '<section data-s="DF"><h2>倒木実費</h2><label>写真番号（カンマ区切り）<input class="photos" inputmode="numeric" placeholder="001, 002"></label></section>';return '<section data-s="FR"><h2>自由記述</h2><label>区分<input class="free-label" placeholder="例: 崖のため伐採不可"></label><label>写真番号（カンマ区切り）<input class="photos" inputmode="numeric" placeholder="001, 002"></label></section>'}function sec(c){let e=form.querySelector(`[data-s="${c}"]`);if(!e){form.insertAdjacentHTML("beforeend",html(c));e=form.lastElementChild}return e}
function entries(e){const a=[];e.querySelectorAll(".run").forEach(r=>{const s=r.querySelector(".start").value.trim(),v=(r.dataset.counts||"").split(",").filter(Boolean).map(Number);if(s&&v.length)v.forEach((count,i)=>a.push({photo:no(Number(s)+i),count}))});return a}function refreshUnder(e){const c=e.dataset.s,state=e.querySelector(".state");let rows;try{rows=entries(e)}catch(err){state.textContent=err.message;state.className="status state warn";return}e.querySelectorAll(".run").forEach(r=>{const v=(r.dataset.counts||"").split(",").filter(Boolean),p=r.dataset.pending||"";r.querySelector(".counts").textContent=v.length?v.map((n,i)=>`写真${i+1}: ${n}本`).join("　"):"まだ確定していません";r.querySelector(".pending").textContent=p?`旧下書きの未確定入力: ${p}本（⌫で破棄。新しい数字は即時確定）`:""});const total=rows.reduce((s,x)=>s+x.count,0),need=plan[c];e.querySelector(".summary").textContent=`入力 ${total}本 / 予定 ${need}本`;if(total<need){state.textContent=`不足 ${need-total}本`;state.className="status state short";e.querySelector(".preview").textContent="";return}if(total===need){state.textContent="予定分完了";state.className="status state ok";e.querySelector(".preview").textContent="台帳: 予定RUNのみ";return}const split=part(rows,need);if(!split.exact){state.textContent="予定分と追加分を写真単位で分けられません";state.className="status state warn";e.querySelector(".preview").textContent="写真を分割せずPC側でも要確認";return}let n=1;const view=a=>a.map(x=>{const end=n+x.count-1,t=`${x.photo}（${n===end?`①${n}`:`①${n}〜${end}`}）`;n=end+1;return t}).join(" → ");state.textContent=`予定分完了・追加 ${total-need}本（候補）`;state.className="status state added";e.querySelector(".preview").textContent=`台帳: 予定RUN ${view(split.planned)} ｜ 追加RUN ${view(split.added)}`}function refreshOne(e){const c=e.dataset.s,n=e.querySelector(".photos").value.split(",").map(x=>x.trim()).filter(Boolean).length,need=plan[c],state=e.querySelector(".state");e.querySelector(".summary").textContent=`入力 ${n}枚 / 予定 ${need}本`;state.textContent=n<need?`不足 ${need-n}本`:n===need?"予定分完了":`予定分完了・追加 ${n-need}本（候補）`;state.className=`status state ${n<need?"short":n===need?"ok":"added"}`}function refresh(){form.querySelectorAll("section[data-s]").forEach(e=>e.dataset.s==="E10"||e.dataset.s==="N10"?refreshUnder(e):cuts.includes(e.dataset.s)&&refreshOne(e))}function refreshChoices(){choices.querySelectorAll("[data-code]").forEach(b=>{const n=qty(b.dataset.code);b.textContent=`${labels[b.dataset.code]}${n?`（予定 ${n}）`:""}`})}function render(){const active=new Set(chosen());codes.forEach(c=>{const e=sec(c);e.classList.toggle("hidden",!active.has(c));if(active.has(c))form.append(e)});refreshChoices();refresh()}
function delta(){return Object.fromEntries(Object.keys(base).filter(k=>plan[k]!==base[k]).map(k=>[k,plan[k]-base[k]]))}function renderPlan(){planCut.innerHTML=bands.map(([e,n,l])=>`<div class="plan-grid"><span class="plan-label">${l}</span><label><input type="number" min="0" step="1" data-plan="${e}" value="${plan[e]}"><small>元 ${base[e]}</small></label><label><input type="number" min="0" step="1" data-plan="${n}" value="${plan[n]}"><small>元 ${base[n]}</small></label></div>`).join("");planOther.innerHTML=others.map(([,k,l])=>`<div class="plan-other"><label>${l}<small> 元 ${base[k]}</small></label><input type="number" min="0" step="1" data-plan="${k}" value="${plan[k]}"></div>`).join("");const d=Object.entries(delta());planSummary.textContent=d.length?`このJSONに反映する修正: ${d.map(([k,v])=>`${k} ${v>0?"+":""}${v}`).join(" / ")}`:"元の予定からの修正はありません。"}function readPlan(){planEdit.querySelectorAll("[data-plan]").forEach(i=>plan[i.dataset.plan]=integer(i.value));cuts.forEach(c=>{if(plan[c]>0)choices.querySelector(`[data-code="${c}"]`).setAttribute("aria-pressed","true")});others.forEach(([c,k])=>{if(plan[k]>0)choices.querySelector(`[data-code="${c}"]`).setAttribute("aria-pressed","true")});renderPlan();refreshChoices();render()}
function snapshot(){const out={version:3,saved_at:new Date().toISOString(),selected:chosen(),design:document.querySelector("#design").value,plan_override:{...plan},pairs:{},runs:{},photos:{},transport:[],special:{}};out.selected.forEach(c=>{const e=sec(c);if(pairs.includes(c)){out.pairs[c]=[...e.querySelectorAll(".pair")].map(r=>({before:r.querySelector(".before").value,after:r.querySelector(".after").value}));if(c==="TK")out.pairs.TK_reuse=e.querySelector(".reuse").value}else if(c==="E10"||c==="N10")out.runs[c]=[...e.querySelectorAll(".run")].map(r=>({start:r.querySelector(".start").value,counts:r.dataset.counts||"",pending:r.dataset.pending||""}));else if(cuts.includes(c)||c==="DF")out.photos[c]=e.querySelector(".photos").value;else if(c==="US")out.transport=[...e.querySelectorAll(".transport-row")].map(r=>({vehicle:r.querySelector(".vehicle").value,specified:r.querySelector(".specified").checked,photos:r.querySelector(".transport-photos").value}));else out.special.FR={label:e.querySelector(".free-label").value,photos:e.querySelector(".photos").value}});return out}
function apply(s){if(!s||!Array.isArray(s.selected))throw Error("下書きの形式を確認できません");Object.keys(base).forEach(k=>{if(Object.hasOwn(s.plan_override||{},k))plan[k]=integer(s.plan_override[k])});designInput.value=String(s.design||"");planDesignInput.value=designInput.value;const active=new Set(s.selected.filter(c=>codes.includes(c)));if(!active.size)defaults().forEach(c=>active.add(c));choices.querySelectorAll("[data-code]").forEach(b=>b.setAttribute("aria-pressed",active.has(b.dataset.code)));renderPlan();render();[...active].forEach(c=>{const e=sec(c);if(pairs.includes(c)){e.querySelector(".pair-list").innerHTML="";(s.pairs?.[c]||[]).forEach(r=>e.querySelector(".pair-list").insertAdjacentHTML("beforeend",pair(r.before||"",r.after||"")));if(!e.querySelector(".pair-list").children.length)e.querySelector(".pair-list").insertAdjacentHTML("beforeend",pair());if(c==="TK")e.querySelector(".reuse").value=String(s.pairs?.TK_reuse||"")}else if(c==="E10"||c==="N10"){e.querySelector(".runs").innerHTML="";(s.runs?.[c]||[]).forEach(r=>e.querySelector(".runs").insertAdjacentHTML("beforeend",run(r.start||"",String(r.counts||"").split(",").filter(Boolean),r.pending||"")));if(!e.querySelector(".runs").children.length)e.querySelector(".runs").insertAdjacentHTML("beforeend",run())}else if(cuts.includes(c)||c==="DF")e.querySelector(".photos").value=String(s.photos?.[c]||"");else if(c==="US"){e.querySelector(".transport-list").innerHTML="";(s.transport||[]).forEach(r=>e.querySelector(".transport-list").insertAdjacentHTML("beforeend",transport(r.vehicle||"軽四輪",!!r.specified,r.photos||"")));if(!e.querySelector(".transport-list").children.length)e.querySelector(".transport-list").insertAdjacentHTML("beforeend",transport())}else{e.querySelector(".free-label").value=String(s.special?.FR?.label||"");e.querySelector(".photos").value=String(s.special?.FR?.photos||"")}});refresh()}
function fromOld(saved){const d=saved?.data;if(!d||!Array.isArray(saved.selected))throw Error("旧下書きの形式を確認できません");const o={selected:saved.selected,design:d.case?.design_no||"",pairs:{},runs:{},photos:{},transport:[],special:{}};pairs.forEach(c=>{const rows=d.pairs?.[c]||[];o.pairs[c]=rows.filter(r=>!(c==="TK"&&r.reuse_ba_pair_indexes?.length)).map(r=>({before:r.before||"",after:r.after||""}));if(c==="TK")o.pairs.TK_reuse=rows.flatMap(r=>r.reuse_ba_pair_indexes||[]).join(",")});["E10","N10"].forEach(c=>o.runs[c]=(d.cuts?.[c]||[]).map(r=>({start:r.start_photo||"",counts:(r.counts||[]).join(","),pending:""})));cuts.filter(c=>c!=="E10"&&c!=="N10").forEach(c=>o.photos[c]=(d.cuts?.[c]||[]).join(", "));o.transport=(d.transport||[]).map(r=>{const m=String(r.label||"").match(/^(指定場所運搬|運搬)\s+(軽四輪|2t車)$/);return m?{vehicle:m[2],specified:m[1]==="指定場所運搬",photos:(r.photos||[]).join(", ")}:null}).filter(Boolean);const df=(d.special||[]).find(r=>r.label==="倒木実費"),fr=(d.special||[]).find(r=>r.label!=="倒木実費");o.photos.DF=df?(df.photos||[]).join(", "):"";o.special.FR=fr?{label:fr.label||"",photos:(fr.photos||[]).join(", ")}:{label:"",photos:""};return o}
const get=k=>{try{return localStorage.getItem(k)}catch(e){say(`端末内下書きを読めません: ${e.message}`,"warn");return null}};function persist(){try{const serial=JSON.stringify(snapshot()),prior=get(key);if(prior&&prior!==serial){const prev=get(backupKey);if(prev&&prev!==prior)localStorage.setItem(olderBackupKey,prev);localStorage.setItem(backupKey,prior)}localStorage.setItem(key,serial);say("端末内の下書きを自動保存しました","ok")}catch(e){say(`下書きは削除していません。保存できませんでした: ${e.message}`,"warn")}}function restore(){const a=[{k:key,t:"端末内の下書きを読み込みました"},{k:backupKey,t:"予備の下書きを読み込みました"},{k:olderBackupKey,t:"一つ前の予備下書きを読み込みました"},{k:oldKey,t:"旧形式の端末内下書きを読み込みました",old:true}],bad=[];for(const c of a){const raw=get(c.k);if(!raw)continue;try{apply(c.old?fromOld(JSON.parse(raw)):JSON.parse(raw));say(c.t,"ok");return}catch(e){bad.push(e)}}if(bad.length)say("下書きを復元できませんでしたが、端末内のデータは削除していません。連絡してください。","warn")}
function collect(){const planned=Object.fromEntries(cuts.map(c=>[c,plan[c]])),original=Object.fromEntries(cuts.map(c=>[c,base[c]]));const data={schema:"ippatsu-photo-ledger-instruction/v1",created_at:new Date().toISOString(),case:{share_date_key:q.get("date")||"",design_no:document.querySelector("#design").value.trim(),management_no:mno,span_label:span,planned,original_planned:original,felling_plan:{branch_cuts:[plan.E10,plan.E20,plan.E30,plan.E40,plan.E50,plan.E60],root_cuts:[plan.N10,plan.N20,plan.N30,plan.N40,plan.N50,plan.N60],brush_area_m2:plan.brush_area_m2,bamboo_count:plan.bamboo_count,vine_locations:plan.vine_locations},plan_adjustment:{original:{...base},final:{...plan},delta:delta(),storage:"instruction_json_only"}},pairs:{BA:[],TK:[],SB:[],TR:[]},cuts:Object.fromEntries(cuts.map(c=>[c,[]])),transport:[],special:[]};chosen().forEach(c=>{const e=sec(c);if(pairs.includes(c)){e.querySelectorAll(".pair").forEach(r=>{const a=r.querySelector(".before").value.trim(),b=r.querySelector(".after").value.trim();if(a||b)data.pairs[c].push({before:no(a),after:no(b)})});if(c==="TK")e.querySelector(".reuse").value.split(",").map(x=>x.trim()).filter(Boolean).forEach(v=>{const i=Number(v),ba=data.pairs.BA[i-1];if(!Number.isInteger(i)||!ba)throw Error("竹のBA流用組番号を確認してください");data.pairs.TK.push({...ba,reuse_ba_pair_indexes:[i]})})}else if(c==="E10"||c==="N10")e.querySelectorAll(".run").forEach(r=>{const s=r.querySelector(".start").value.trim(),v=(r.dataset.counts||"").split(",").filter(Boolean).map(Number);if(s||v.length){if(!s||!v.length)throw Error(`${c} の開始写真番号と本数を入力してください`);data.cuts[c].push({start_photo:no(s),counts:v})}});else if(cuts.includes(c))data.cuts[c]=photos(e.querySelector(".photos").value);else if(c==="US")e.querySelectorAll(".transport-row").forEach(r=>{const p=photos(r.querySelector(".transport-photos").value);if(p.length)data.transport.push({label:`${r.querySelector(".specified").checked?"指定場所運搬":"運搬"} ${r.querySelector(".vehicle").value}`,photos:p})});else if(c==="DF"){const p=photos(e.querySelector(".photos").value);if(p.length)data.special.push({label:"倒木実費",photos:p})}else{const l=e.querySelector(".free-label").value.trim(),p=photos(e.querySelector(".photos").value);if(l||p.length){if(!l||!p.length)throw Error("自由記述は区分と写真番号の両方を入力してください");data.special.push({label:l,photos:p})}}});return data}
codes.forEach(c=>choices.insertAdjacentHTML("beforeend",`<button type="button" class="choice" data-code="${c}" aria-pressed="${c==="BA"||qty(c)>0}"></button>`));choices.addEventListener("click",e=>{const b=e.target.closest("[data-code]");if(!b)return;b.setAttribute("aria-pressed",b.getAttribute("aria-pressed")!=="true");render();persist()});form.addEventListener("click",e=>{const s=e.target.closest("section[data-s]");if(!s)return;if(e.target.closest(".add-pair"))s.querySelector(".pair-list").insertAdjacentHTML("beforeend",pair());if(e.target.closest(".add-run"))s.querySelector(".runs").insertAdjacentHTML("beforeend",run());if(e.target.closest(".add-transport"))s.querySelector(".transport-list").insertAdjacentHTML("beforeend",transport());const b=e.target.closest("[data-key]");if(b){const r=b.closest(".run"),k=b.dataset.key;let p=r.dataset.pending||"";if(k==="back")p=p.slice(0,-1);else if(k==="enter"){if(p&&Number(p)>0){r.dataset.counts=[...(r.dataset.counts?r.dataset.counts.split(","):[]),String(Number(p))].join(",");p=""}}else p+=k;r.dataset.pending=p;refreshUnder(s)}persist()});form.addEventListener("input",()=>{refresh();persist()});form.addEventListener("change",persist);designInput.addEventListener("input",()=>{planDesignInput.value=designInput.value;persist()});document.querySelector("#save").onclick=persist;document.querySelector("#open-plan-edit").onclick=()=>{planEdit.classList.toggle("hidden");if(!planEdit.classList.contains("hidden"))planEdit.scrollIntoView({behavior:"smooth",block:"start"})};planEdit.addEventListener("input",e=>{if(e.target===planDesignInput){designInput.value=planDesignInput.value;persist();return}readPlan();persist()});document.querySelector("#reset-plan").onclick=()=>{plan={...base};renderPlan();refreshChoices();refresh();persist();say("台帳用の予定値を元の指示書の値へ戻しました","ok")};document.querySelector("#clear").onclick=()=>{if(!window.confirm("このケースの端末内下書きと予備下書きを削除しますか？ JSONを保存済みか確認してください。"))return;try{[key,backupKey,olderBackupKey,oldKey].forEach(k=>localStorage.removeItem(k));say("このケースの端末内下書きを削除しました","ok")}catch(e){say(`下書きを削除できませんでした: ${e.message}`,"warn")}};document.querySelector("#download").onclick=()=>{try{const d=collect(),blob=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${q.get("date")||"date"}_${mno}_写真台帳指示.json`;a.click();URL.revokeObjectURL(a.href);persist();say("JSONを保存しました。端末内下書きと予備下書きは残しています。","ok")}catch(e){persist();say(e.message,"warn")}};restore();planDesignInput.value=designInput.value;renderPlan();render();if(q.get("edit_plan")==="1")planEdit.classList.remove("hidden");
async function savePortalDraft(){const button=document.querySelector("#portal-save");try{const document=collect();button.disabled=true;say("ポータルへ保存中…");const response=await fetch(portalDraftEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(document)});if(!response.ok)throw Error("ポータル保存に失敗しました");persist();say("ポータルに保存しました。PC GUIから直接開けます。","ok")}catch(error){persist();say(error.message||"ポータル保存に失敗しました。端末内下書きは残っています。","warn")}finally{button.disabled=false}}document.querySelector("#portal-save").onclick=savePortalDraft;
function installBaReuseControls(){
  const reusableCodes=["TR","SB"];
  const controls=[];
  const sync=control=>{
    const values=control.input.value.split(",").map(value=>value.trim()).filter(Boolean);
    const selected=[];
    const baPairs=[...sec("BA").querySelectorAll(".pair")];
    for(const value of values){
      const index=Number(value),source=baPairs[index-1];
      if(!Number.isInteger(index)||!source||!source.querySelector(".before").value.trim()||!source.querySelector(".after").value.trim()){
        control.input.setCustomValidity("BA流用する組番号を確認してください");
        return;
      }
      selected.push({before:source.querySelector(".before").value.trim(),after:source.querySelector(".after").value.trim()});
    }
    control.input.setCustomValidity("");
    const list=control.section.querySelector(".pair-list");
    list.querySelectorAll("[data-ba-reuse=true]").forEach(row=>row.remove());
    selected.forEach(row=>{
      list.insertAdjacentHTML("beforeend",pair(row.before,row.after));
      list.lastElementChild.dataset.baReuse="true";
    });
    refresh();persist();
  };
  reusableCodes.forEach(code=>{
    const section=sec(code);
    section.insertAdjacentHTML("beforeend",'<label class="ba-reuse"><span>BA流用する組番号（例: 1,2）</span><input inputmode="numeric" placeholder="例: 1,2"></label><p class="note">指定した伐採前後の組を、この区分にも掲載します。</p>');
    const input=section.querySelector(".ba-reuse input");
    const control={section,input};
    controls.push(control);
    input.addEventListener("input",()=>sync(control));
  });
  sec("BA").addEventListener("input",()=>controls.forEach(control=>{
    if(control.input.value.trim())sync(control);
  }));
}
installBaReuseControls();
// E10/N10 は1〜9のタップをその写真の本数として即時確定する。旧版の
// バブリング用ハンドラを残しても、ここを capture で処理して二重入力を防ぐ。
form.addEventListener("click",event=>{
  const button=event.target.closest("[data-key]");
  if(!button)return;
  const section=button.closest("section[data-s]");
  const runRow=button.closest(".run");
  if(!section||!runRow||!(section.dataset.s==="E10"||section.dataset.s==="N10"))return;
  const keyName=button.dataset.key;
  const counts=(runRow.dataset.counts||"").split(",").filter(Boolean);
  if(keyName==="back"){
    // 旧版で保存された未確定数は出力へ含めず、明示的に破棄できる。
    if(runRow.dataset.pending)runRow.dataset.pending="";
    else counts.pop();
  }else if(/^[1-9]$/.test(keyName)){
    counts.push(keyName);
    runRow.dataset.pending="";
  }else return;
  runRow.dataset.counts=counts.join(",");
  event.preventDefault();
  event.stopImmediatePropagation();
  refreshUnder(section);
  persist();
},true);
})();
