(() => {
  "use strict";
  const q = new URLSearchParams(location.search), codes = ["BA","E10","E20","E30","E40","E50","E60","N10","N20","N30","N40","N50","N60","TK","TR","SB","US","DF","FR"], cuts = codes.filter((x) => /^[EN]\d\d$/.test(x)), pairs = ["BA","TK","TR","SB"], mno = q.get("management_no") || "", span = q.get("label") || "", form = document.querySelector("#form"), choices = document.querySelector("#choices"), message = document.querySelector("#message"), plan = Object.fromEntries(cuts.map((x) => [x, Number(q.get(x) || 0)])), oldKey = `ippatsu-photo-ledger-draft:${[q.get("date") || "", mno, span].join(":")}`, key = `ippatsu-photo-ledger-draft:v2:${[q.get("date") || "", mno].join(":")}`, backupKey = `${key}:backup`, olderBackupKey = `${key}:backup-previous`;
  const labels = {BA:"伐採前後",E10:"E10",E20:"E20",E30:"E30",E40:"E40",E50:"E50",E60:"E60",N10:"N10",N20:"N20",N30:"N30",N40:"N40",N50:"N50",N60:"N60",TK:"竹伐採前後",TR:"つる伐採前後",SB:"柴伐採前後",US:"運搬",DF:"倒木実費",FR:"自由記述"};
  document.querySelector("#case").textContent = `${mno}　${span}`;
  const say = (text, kind = "") => { message.textContent = text; message.className = `message ${kind}`.trim(); };
  const no = (v) => { v = String(v || "").trim(); if (!/^\d{1,3}$/.test(v)) throw Error("写真番号は1〜3桁の数字です"); return v.padStart(3, "0"); };
  const photos = (v) => String(v || "").split(",").map((x) => x.trim()).filter(Boolean).map(no);
  const selected = () => [...choices.querySelectorAll("[aria-pressed=true]")].map((x) => x.dataset.code);
  const defaults = () => codes.filter((x) => x === "BA" || plan[x] > 0);
  function part(rows, target) { const reachable = new Map([[0, []]]); rows.forEach((row, index) => [...reachable].forEach(([sum, indexes]) => { const next = sum + row.count; if (next <= target && !reachable.has(next)) reachable.set(next, [...indexes, index]); })); const exact = reachable.has(target), picked = new Set(reachable.get(exact ? target : Math.max(...reachable.keys()))); return {exact, planned: rows.filter((_, index) => picked.has(index)), added: rows.filter((_, index) => !picked.has(index))}; }
  const pairRow = (before = "", after = "") => `<div class="pair"><label>前<input class="before" inputmode="numeric" value="${before}"></label><label>後<input class="after" inputmode="numeric" value="${after}"></label></div>`;
  const runRow = (start = "", counts = [], pending = "") => `<div class="run" data-counts="${counts.join(",")}" data-pending="${pending}"><label>開始写真番号<input class="start" inputmode="numeric" value="${start}" placeholder="001"></label><label>写真ごとの本数</label><div class="counts"></div><div class="keys">${[1,2,3,4,5,6,7,8,9].map((n) => `<button type="button" class="key" data-key="${n}">${n}</button>`).join("")}<button type="button" class="key" data-key="back">⌫</button><button type="button" class="key" data-key="0">0</button><button type="button" class="key enter" data-key="enter">確定</button></div><small class="pending"></small></div>`;
  const transportRow = (vehicle = "軽四輪", specified = false, photoText = "") => `<div class="transport-row"><label>車種<select class="vehicle"><option ${vehicle === "軽四輪" ? "selected" : ""}>軽四輪</option><option ${vehicle === "2t車" ? "selected" : ""}>2t車</option></select></label><label>写真番号（カンマ区切り）<input class="transport-photos" inputmode="numeric" value="${photoText}"></label><label class="transport-check"><input class="specified" type="checkbox" ${specified ? "checked" : ""}>指定場所運搬にする</label></div>`;
  function sectionHtml(code) {
    if (pairs.includes(code)) return `<section data-s="${code}"><h2>${labels[code]}</h2><small>採用する組だけ入力します。</small><div class="pair-list">${pairRow()}</div><button type="button" class="secondary add-pair">＋ 前後1組を追加</button>${code === "TK" ? '<label>BA流用する組番号（例: 1,2）<input class="reuse" inputmode="numeric"></label><p class="note">指定したBA組だけを竹伐採前後にも使います。</p>' : ""}</section>`;
    if (code === "E10" || code === "N10") return `<section data-s="${code}"><h2>${code} <span class="status summary"></span></h2><small>写真ごとの本数をテンキーで確定。写真番号が飛ぶ時だけ続きの写真を追加。</small><div class="runs">${runRow()}</div><button type="button" class="secondary add-run">＋ 続きの写真を追加</button><p class="status state" aria-live="polite"></p><p class="note preview"></p></section>`;
    if (cuts.includes(code)) return `<section data-s="${code}"><h2>${code} <span class="status summary"></span></h2><small>1本につき写真1枚です。</small><label>写真番号（カンマ区切り）<input class="photos" inputmode="numeric" placeholder="001, 002"></label><p class="status state" aria-live="polite"></p></section>`;
    if (code === "US") return `<section data-s="US"><h2>運搬</h2><small>車種を選び、チェック中だけ「指定場所運搬」として保存します。</small><div class="transport-list">${transportRow()}</div><button type="button" class="secondary add-transport">＋ 運搬を追加</button></section>`;
    if (code === "DF") return '<section data-s="DF"><h2>倒木実費</h2><label>写真番号（カンマ区切り）<input class="photos" inputmode="numeric" placeholder="001, 002"></label></section>';
    return '<section data-s="FR"><h2>自由記述</h2><label>区分<input class="free-label" placeholder="例: 崖のため伐採不可"></label><label>写真番号（カンマ区切り）<input class="photos" inputmode="numeric" placeholder="001, 002"></label></section>';
  }
  function sec(code) { let e = form.querySelector(`[data-s="${code}"]`); if (!e) { form.insertAdjacentHTML("beforeend", sectionHtml(code)); e = form.lastElementChild; } return e; }
  function entries(e) { const rows = []; e.querySelectorAll(".run").forEach((r) => { const start = r.querySelector(".start").value.trim(), counts = (r.dataset.counts || "").split(",").filter(Boolean).map(Number); if (start && counts.length) counts.forEach((count, index) => rows.push({photo:no(Number(start) + index), count})); }); return rows; }
  function refreshUnder(e) { const code = e.dataset.s, state = e.querySelector(".state"); let rows; try { rows = entries(e); } catch (err) { state.textContent = err.message; state.className = "status state warn"; return; } e.querySelectorAll(".run").forEach((r) => { const values = (r.dataset.counts || "").split(",").filter(Boolean), pending = r.dataset.pending || ""; r.querySelector(".counts").textContent = values.length ? values.map((v, i) => `写真${i + 1}: ${v}本`).join("　") : "まだ確定していません"; r.querySelector(".pending").textContent = pending ? `入力中: ${pending}本` : ""; }); const total = rows.reduce((sum, row) => sum + row.count, 0), needed = plan[code]; e.querySelector(".summary").textContent = `入力 ${total}本 / 予定 ${needed}本`; if (total < needed) { state.textContent = `不足 ${needed - total}本`; state.className = "status state short"; e.querySelector(".preview").textContent = ""; return; } if (total === needed) { state.textContent = "予定分完了"; state.className = "status state ok"; e.querySelector(".preview").textContent = "台帳: 予定RUNのみ"; return; } const split = part(rows, needed); if (!split.exact) { state.textContent = "予定分と追加分を写真単位で分けられません"; state.className = "status state warn"; e.querySelector(".preview").textContent = "写真を分割せずPC側でも要確認"; return; } const view = (items) => { let n = 1; return items.map((item) => { const end = n + item.count - 1, text = `${item.photo}（${n === end ? `①${n}` : `①${n}〜${end}`}）`; n = end + 1; return text; }).join(" → "); }; state.textContent = `予定分完了・追加 ${total - needed}本（候補）`; state.className = "status state added"; e.querySelector(".preview").textContent = `台帳: 予定RUN ${view(split.planned)} ｜ 追加RUN ${view(split.added)}`; }
  function refreshOne(e) { const code = e.dataset.s, count = e.querySelector(".photos").value.split(",").map((x) => x.trim()).filter(Boolean).length, needed = plan[code], state = e.querySelector(".state"); e.querySelector(".summary").textContent = `入力 ${count}枚 / 予定 ${needed}本`; state.textContent = count < needed ? `不足 ${needed - count}本` : count === needed ? "予定分完了" : `予定分完了・追加 ${count - needed}本（候補）`; state.className = `status state ${count < needed ? "short" : count === needed ? "ok" : "added"}`; }
  function refresh() { form.querySelectorAll("section[data-s]").forEach((e) => { if (e.dataset.s === "E10" || e.dataset.s === "N10") refreshUnder(e); else if (cuts.includes(e.dataset.s)) refreshOne(e); }); }
  function render() { const active = new Set(selected()); codes.forEach((code) => { const e = sec(code); e.classList.toggle("hidden", !active.has(code)); if (active.has(code)) form.append(e); }); refresh(); }
  function rawSnapshot() { const out = {version:2,saved_at:new Date().toISOString(),selected:selected(),design:document.querySelector("#design").value,pairs:{},runs:{},photos:{},transport:[],special:{}}; out.selected.forEach((code) => { const e = sec(code); if (pairs.includes(code)) { out.pairs[code] = [...e.querySelectorAll(".pair")].map((row) => ({before:row.querySelector(".before").value,after:row.querySelector(".after").value})); if (code === "TK") out.pairs.TK_reuse = e.querySelector(".reuse").value; } else if (code === "E10" || code === "N10") out.runs[code] = [...e.querySelectorAll(".run")].map((r) => ({start:r.querySelector(".start").value,counts:r.dataset.counts || "",pending:r.dataset.pending || ""})); else if (cuts.includes(code) || code === "DF") out.photos[code] = e.querySelector(".photos").value; else if (code === "US") out.transport = [...e.querySelectorAll(".transport-row")].map((r) => ({vehicle:r.querySelector(".vehicle").value,specified:r.querySelector(".specified").checked,photos:r.querySelector(".transport-photos").value})); else if (code === "FR") out.special.FR = {label:e.querySelector(".free-label").value,photos:e.querySelector(".photos").value}; }); return out; }
  function applySnapshot(data) { if (!data || !Array.isArray(data.selected)) throw Error("下書きの形式を確認できません"); document.querySelector("#design").value = String(data.design || ""); const active = new Set(data.selected.filter((x) => codes.includes(x))); if (!active.size) defaults().forEach((x) => active.add(x)); choices.querySelectorAll("[data-code]").forEach((b) => b.setAttribute("aria-pressed", active.has(b.dataset.code))); render(); [...active].forEach((code) => { const e = sec(code); if (pairs.includes(code)) { e.querySelector(".pair-list").innerHTML = ""; (Array.isArray(data.pairs?.[code]) ? data.pairs[code] : []).forEach((r) => e.querySelector(".pair-list").insertAdjacentHTML("beforeend", pairRow(r.before || "", r.after || ""))); if (!e.querySelector(".pair-list").children.length) e.querySelector(".pair-list").insertAdjacentHTML("beforeend", pairRow()); if (code === "TK") e.querySelector(".reuse").value = String(data.pairs?.TK_reuse || ""); } else if (code === "E10" || code === "N10") { e.querySelector(".runs").innerHTML = ""; (Array.isArray(data.runs?.[code]) ? data.runs[code] : []).forEach((r) => e.querySelector(".runs").insertAdjacentHTML("beforeend", runRow(r.start || "", String(r.counts || "").split(",").filter(Boolean), r.pending || ""))); if (!e.querySelector(".runs").children.length) e.querySelector(".runs").insertAdjacentHTML("beforeend", runRow()); } else if (cuts.includes(code) || code === "DF") e.querySelector(".photos").value = String(data.photos?.[code] || ""); else if (code === "US") { e.querySelector(".transport-list").innerHTML = ""; (Array.isArray(data.transport) ? data.transport : []).forEach((r) => e.querySelector(".transport-list").insertAdjacentHTML("beforeend", transportRow(r.vehicle || "軽四輪", Boolean(r.specified), r.photos || ""))); if (!e.querySelector(".transport-list").children.length) e.querySelector(".transport-list").insertAdjacentHTML("beforeend", transportRow()); } else if (code === "FR") { e.querySelector(".free-label").value = String(data.special?.FR?.label || ""); e.querySelector(".photos").value = String(data.special?.FR?.photos || ""); } }); refresh(); }
  function oldSnapshot(saved) { const data = saved?.data; if (!data || !Array.isArray(saved.selected)) throw Error("旧下書きの形式を確認できません"); const out = {version:2,selected:saved.selected,design:data.case?.design_no || "",pairs:{},runs:{},photos:{},transport:[],special:{}}; pairs.forEach((code) => { const rows = Array.isArray(data.pairs?.[code]) ? data.pairs[code] : []; out.pairs[code] = rows.filter((r) => !(code === "TK" && r.reuse_ba_pair_indexes?.length)).map((r) => ({before:r.before || "",after:r.after || ""})); if (code === "TK") out.pairs.TK_reuse = rows.flatMap((r) => r.reuse_ba_pair_indexes || []).join(","); }); ["E10","N10"].forEach((code) => { out.runs[code] = (data.cuts?.[code] || []).map((r) => ({start:r.start_photo || "",counts:(r.counts || []).join(","),pending:""})); }); cuts.filter((code) => code !== "E10" && code !== "N10").forEach((code) => { out.photos[code] = (data.cuts?.[code] || []).join(", "); }); out.transport = (data.transport || []).map((r) => { const m = String(r.label || "").match(/^(指定場所運搬|運搬)\s+(軽四輪|2t車)$/); return m ? {vehicle:m[2],specified:m[1] === "指定場所運搬",photos:(r.photos || []).join(", ")} : null; }).filter(Boolean); const fallen = (data.special || []).find((r) => r.label === "倒木実費"), free = (data.special || []).find((r) => r.label !== "倒木実費"); out.photos.DF = fallen ? (fallen.photos || []).join(", ") : ""; out.special.FR = free ? {label:free.label || "",photos:(free.photos || []).join(", ")} : {label:"",photos:""}; return out; }
  const get = (storageKey) => { try { return localStorage.getItem(storageKey); } catch (error) { say(`端末内下書きを読めません: ${error.message}`, "warn"); return null; } };
  function persist() { try { const serial = JSON.stringify(rawSnapshot()), prior = get(key); if (prior && prior !== serial) { const previousBackup = get(backupKey); if (previousBackup && previousBackup !== prior) localStorage.setItem(olderBackupKey, previousBackup); localStorage.setItem(backupKey, prior); } localStorage.setItem(key, serial); say("端末内の下書きを自動保存しました", "ok"); } catch (error) { say(`下書きは削除していません。保存できませんでした: ${error.message}`, "warn"); } }
  function restore() { const candidates = [{storageKey:key,title:"端末内の下書きを読み込みました"},{storageKey:backupKey,title:"予備の下書きを読み込みました"},{storageKey:olderBackupKey,title:"一つ前の予備下書きを読み込みました"},{storageKey:oldKey,title:"旧形式の端末内下書きを読み込みました",old:true}], failures = []; for (const candidate of candidates) { const raw = get(candidate.storageKey); if (!raw) continue; try { const parsed = JSON.parse(raw); applySnapshot(candidate.old ? oldSnapshot(parsed) : parsed); say(candidate.title, "ok"); return; } catch (error) { failures.push(error); } } if (failures.length) say("下書きを復元できませんでしたが、端末内のデータは削除していません。連絡してください。", "warn"); }
  function collect() { const data = {schema:"ippatsu-photo-ledger-instruction/v1",created_at:new Date().toISOString(),case:{share_date_key:q.get("date") || "",design_no:document.querySelector("#design").value.trim(),management_no:mno,span_label:span,planned:plan},pairs:{BA:[],TK:[],SB:[],TR:[]},cuts:Object.fromEntries(cuts.map((code) => [code,[]])),transport:[],special:[]}; selected().forEach((code) => { const e = sec(code); if (pairs.includes(code)) { e.querySelectorAll(".pair").forEach((r) => { const before = r.querySelector(".before").value.trim(), after = r.querySelector(".after").value.trim(); if (before || after) data.pairs[code].push({before:no(before),after:no(after)}); }); if (code === "TK") e.querySelector(".reuse").value.split(",").map((x) => x.trim()).filter(Boolean).forEach((value) => { const index = Number(value), ba = data.pairs.BA[index - 1]; if (!Number.isInteger(index) || !ba) throw Error("竹のBA流用組番号を確認してください"); data.pairs.TK.push({...ba,reuse_ba_pair_indexes:[index]}); }); } else if (code === "E10" || code === "N10") e.querySelectorAll(".run").forEach((r) => { const start = r.querySelector(".start").value.trim(), counts = (r.dataset.counts || "").split(",").filter(Boolean).map(Number); if (start || counts.length) { if (!start || !counts.length) throw Error(`${code} の開始写真番号と本数を入力してください`); data.cuts[code].push({start_photo:no(start),counts}); } }); else if (cuts.includes(code)) data.cuts[code] = photos(e.querySelector(".photos").value); else if (code === "US") e.querySelectorAll(".transport-row").forEach((r) => { const picked = photos(r.querySelector(".transport-photos").value); if (picked.length) data.transport.push({label:`${r.querySelector(".specified").checked ? "指定場所運搬" : "運搬"} ${r.querySelector(".vehicle").value}`,photos:picked}); }); else if (code === "DF") { const picked = photos(e.querySelector(".photos").value); if (picked.length) data.special.push({label:"倒木実費",photos:picked}); } else { const freeLabel = e.querySelector(".free-label").value.trim(), picked = photos(e.querySelector(".photos").value); if (freeLabel || picked.length) { if (!freeLabel || !picked.length) throw Error("自由記述は区分と写真番号の両方を入力してください"); data.special.push({label:freeLabel,photos:picked}); } } }); return data; }
  codes.forEach((code) => choices.insertAdjacentHTML("beforeend", `<button type="button" class="choice" data-code="${code}" aria-pressed="${code === "BA" || plan[code] > 0}">${labels[code]}${plan[code] ? `（予定 ${plan[code]}）` : ""}</button>`));
  choices.addEventListener("click", (event) => { const button = event.target.closest("[data-code]"); if (!button) return; button.setAttribute("aria-pressed", button.getAttribute("aria-pressed") !== "true"); render(); persist(); });
  form.addEventListener("click", (event) => { const e = event.target.closest("section[data-s]"); if (!e) return; if (event.target.closest(".add-pair")) e.querySelector(".pair-list").insertAdjacentHTML("beforeend", pairRow()); if (event.target.closest(".add-run")) e.querySelector(".runs").insertAdjacentHTML("beforeend", runRow()); if (event.target.closest(".add-transport")) e.querySelector(".transport-list").insertAdjacentHTML("beforeend", transportRow()); const button = event.target.closest("[data-key]"); if (button) { const r = button.closest(".run"), action = button.dataset.key; let pending = r.dataset.pending || ""; if (action === "back") pending = pending.slice(0, -1); else if (action === "enter") { if (pending && Number(pending) > 0) { r.dataset.counts = [...(r.dataset.counts ? r.dataset.counts.split(",") : []),String(Number(pending))].join(","); pending = ""; } } else pending += action; r.dataset.pending = pending; refreshUnder(e); } persist(); });
  form.addEventListener("input", () => { refresh(); persist(); }); form.addEventListener("change", persist); document.querySelector("#design").addEventListener("input", persist); document.querySelector("#save").onclick = persist;
  document.querySelector("#clear").onclick = () => { if (!window.confirm("このケースの端末内下書きと予備下書きを削除しますか？ JSONを保存済みか確認してください。")) return; try { [key,backupKey,olderBackupKey,oldKey].forEach((storageKey) => localStorage.removeItem(storageKey)); say("このケースの端末内下書きを削除しました", "ok"); } catch (error) { say(`下書きを削除できませんでした: ${error.message}`, "warn"); } };
  document.querySelector("#download").onclick = () => { try { const data = collect(), blob = new Blob([JSON.stringify(data,null,2)], {type:"application/json"}), anchor = document.createElement("a"); anchor.href = URL.createObjectURL(blob); anchor.download = `${q.get("date") || "date"}_${mno}_写真台帳指示.json`; anchor.click(); URL.revokeObjectURL(anchor.href); persist(); say("JSONを保存しました。端末内下書きと予備下書きは残しています。", "ok"); } catch (error) { persist(); say(error.message, "warn"); } };
  restore(); render();
})();
